from contextlib import suppress

import peewee as pw
from peewee_migrate import Migrator


with suppress(ImportError):
    import playhouse.postgres_ext as pw_pext


def migrate(migrator: Migrator, database: pw.Database, *, fake=False):
    """Add ai_generated boolean field to Sourcefile table.

    This field indicates whether the sourcefile was generated by AI (True) or imported from a real source (False).
    """

    # Define the model to add field to
    class Sourcefile(pw.Model):
        ai_generated = pw.BooleanField(default=False)

        class Meta:
            table_name = "sourcefile"

    with database.atomic():
        # 1. Add the column as nullable first
        migrator.add_fields(
            Sourcefile, ai_generated=pw.BooleanField(null=True, default=False)
        )

        # 2. Fill existing rows with default value (False)
        migrator.sql("UPDATE sourcefile SET ai_generated = FALSE")

        # 3. Set the column to NOT NULL
        migrator.sql("ALTER TABLE sourcefile ALTER COLUMN ai_generated SET NOT NULL")


def rollback(migrator: Migrator, database: pw.Database, *, fake=False):
    """Roll back the addition of ai_generated field."""

    # Define the model for rollback
    class Sourcefile(pw.Model):
        class Meta:
            table_name = "sourcefile"

    with database.atomic():
        migrator.remove_fields(Sourcefile, "ai_generated")
